[phases.setup]
nixPkgs = ["nodejs", "npm"]
aptPkgs = [
    "wget",
    "ca-certificates",
    "fonts-liberation",
    "libappindicator3-1",
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libcups2",
    "libdbus-1-3",
    "libdrm2",
    "libgbm1",
    "libgtk-3-0",
    "libnspr4",
    "libnss3",
    "libx11-xcb1",
    "libxcomposite1",
    "libxdamage1",
    "libxrandr2",
    "xdg-utils",
    "libnss3",
    "libnspr4",
    "libdbus-1-3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libxkbcommon0",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "libxrandr2",
    "libgbm1",
    "libpango-1.0-0",
    "libcairo2",
    "libasound2"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx playwright install chromium --with-deps"]

[start]
cmd = "npm start"
